using System.Collections.Generic;

public static class TypeChart
{
    private static readonly Dictionary<(EElementType, EElementType), float> _chart = new()
        {
            { (EElementType.Fire, EElementType.Grass), 2f },
            { (EElementType.Fire, EElementType.Water), 0.5f },
            { (EElementType.Fire, EElementType.Fire), 0.5f },
            { (EElementType.Fire, EElementType.Ice), 2f },
            { (EElementType.Fire, EElementType.Electric), 1f },
            { (EElementType.Fire, EElementType.Ground), 1f },
            { (EElementType.Fire, EElementType.Fly), 1f },
            { (EElementType.Fire, EElementType.Ghost), 1f },
            { (EElementType.Fire, EElementType.Fighting), 1f },
            { (EElementType.Fire, EElementType.Steel), 2f },
            { (EElementType.Fire, EElementType.Psychic), 1f },
            { (EElementType.Fire, EElementType.Fairy), 1f },

            { (EElementType.Water, EElementType.Grass), 0.5f },
            { (EElementType.Water, EElementType.Water), 0.5f },
            { (EElementType.Water, EElementType.Fire), 2f },
            { (EElementType.Water, EElementType.Ice), 1f },
            { (EElementType.Water, EElementType.Electric), 1f },
            { (EElementType.Water, EElementType.Ground), 2f },
            { (EElementType.Water, EElementType.Fly), 1f },
            { (EElementType.Water, EElementType.Ghost), 1f },
            { (EElementType.Water, EElementType.Fighting), 1f },
            { (EElementType.Water, EElementType.Steel), 1f },
            { (EElementType.Water, EElementType.Psychic), 1f },
            { (EElementType.Water, EElementType.Fairy), 1f },

            { (EElementType.Grass, EElementType.Grass), 0.5f },
            { (EElementType.Grass, EElementType.Water), 2f },
            { (EElementType.Grass, EElementType.Fire), 0.5f },
            { (EElementType.Grass, EElementType.Ice), 1f },
            { (EElementType.Grass, EElementType.Electric), 1f },
            { (EElementType.Grass, EElementType.Ground), 2f },
            { (EElementType.Grass, EElementType.Fly), 0.5f },
            { (EElementType.Grass, EElementType.Ghost), 1f },
            { (EElementType.Grass, EElementType.Fighting), 1f },
            { (EElementType.Grass, EElementType.Steel), 1f },
            { (EElementType.Grass, EElementType.Psychic), 1f },
            { (EElementType.Grass, EElementType.Fairy), 1f },

            { (EElementType.Electric, EElementType.Grass), 0.5f },
            { (EElementType.Electric, EElementType.Water), 2f },
            { (EElementType.Electric, EElementType.Fire), 1f },
            { (EElementType.Electric, EElementType.Ice), 1f },
            { (EElementType.Electric, EElementType.Electric), 0.5f },
            { (EElementType.Electric, EElementType.Ground), 0f },
            { (EElementType.Electric, EElementType.Fly), 2f },
            { (EElementType.Electric, EElementType.Ghost), 1f },
            { (EElementType.Electric, EElementType.Fighting), 1f },
            { (EElementType.Electric, EElementType.Steel), 1f },
            { (EElementType.Electric, EElementType.Psychic), 1f },
            { (EElementType.Electric, EElementType.Fairy), 1f },

            { (EElementType.Ice, EElementType.Grass), 2f },
            { (EElementType.Ice, EElementType.Water), 0.5f },
            { (EElementType.Ice, EElementType.Fire), 0.5f },
            { (EElementType.Ice, EElementType.Ice), 0.5f },
            { (EElementType.Ice, EElementType.Electric), 1f },
            { (EElementType.Ice, EElementType.Ground), 2f },
            { (EElementType.Ice, EElementType.Fly), 2f },
            { (EElementType.Ice, EElementType.Ghost), 1f },
            { (EElementType.Ice, EElementType.Fighting), 1f },
            { (EElementType.Ice, EElementType.Steel), 0.5f },
            { (EElementType.Ice, EElementType.Psychic), 1f },
            { (EElementType.Ice, EElementType.Fairy), 1f },

            { (EElementType.Ground, EElementType.Grass), 0.5f },
            { (EElementType.Ground, EElementType.Water), 1f },
            { (EElementType.Ground, EElementType.Fire), 2f },
            { (EElementType.Ground, EElementType.Ice), 1f },
            { (EElementType.Ground, EElementType.Electric), 2f },
            { (EElementType.Ground, EElementType.Ground), 1f },
            { (EElementType.Ground, EElementType.Fly), 0f },
            { (EElementType.Ground, EElementType.Ghost), 1f },
            { (EElementType.Ground, EElementType.Fighting), 1f },
            { (EElementType.Ground, EElementType.Steel), 2f },
            { (EElementType.Ground, EElementType.Psychic), 1f },
            { (EElementType.Ground, EElementType.Fairy), 1f },

            { (EElementType.Fly, EElementType.Grass), 2f },
            { (EElementType.Fly, EElementType.Water), 1f },
            { (EElementType.Fly, EElementType.Fire), 2f },
            { (EElementType.Fly, EElementType.Ice), 1f },
            { (EElementType.Fly, EElementType.Electric), 0.5f },
            { (EElementType.Fly, EElementType.Ground), 1f },
            { (EElementType.Fly, EElementType.Fly), 1f },
            { (EElementType.Fly, EElementType.Ghost), 1f },
            { (EElementType.Fly, EElementType.Fighting), 2f },
            { (EElementType.Fly, EElementType.Steel), 0.5f },
            { (EElementType.Fly, EElementType.Psychic), 1f },
            { (EElementType.Fly, EElementType.Fairy), 1f },

            { (EElementType.Ghost, EElementType.Grass), 1f },
            { (EElementType.Ghost, EElementType.Water), 1f },
            { (EElementType.Ghost, EElementType.Fire), 1f },
            { (EElementType.Ghost, EElementType.Ice), 1f },
            { (EElementType.Ghost, EElementType.Electric), 1f },
            { (EElementType.Ghost, EElementType.Ground), 1f },
            { (EElementType.Ghost, EElementType.Fly), 1f },
            { (EElementType.Ghost, EElementType.Ghost), 2f },
            { (EElementType.Ghost, EElementType.Fighting), 1f },
            { (EElementType.Ghost, EElementType.Steel), 1f },
            { (EElementType.Ghost, EElementType.Psychic), 2f },
            { (EElementType.Ghost, EElementType.Fairy), 1f },

            { (EElementType.Fighting, EElementType.Grass), 1f },
            { (EElementType.Fighting, EElementType.Water), 1f },
            { (EElementType.Fighting, EElementType.Fire), 1f },
            { (EElementType.Fighting, EElementType.Ice), 2f },
            { (EElementType.Fighting, EElementType.Electric), 1f },
            { (EElementType.Fighting, EElementType.Ground), 1f },
            { (EElementType.Fighting, EElementType.Fly), 0.5f },
            { (EElementType.Fighting, EElementType.Ghost), 0f },
            { (EElementType.Fighting, EElementType.Fighting), 1f },
            { (EElementType.Fighting, EElementType.Steel), 2f },
            { (EElementType.Fighting, EElementType.Psychic), 0.5f },
            { (EElementType.Fighting, EElementType.Fairy), 0.5f },

            { (EElementType.Steel, EElementType.Grass), 1f },
            { (EElementType.Steel, EElementType.Water), 0.5f },
            { (EElementType.Steel, EElementType.Fire), 0.5f },
            { (EElementType.Steel, EElementType.Ice), 0.5f },
            { (EElementType.Steel, EElementType.Electric), 0.5f },
            { (EElementType.Steel, EElementType.Ground), 1f },
            { (EElementType.Steel, EElementType.Fly), 1f },
            { (EElementType.Steel, EElementType.Ghost), 1f },
            { (EElementType.Steel, EElementType.Fighting), 1f },
            { (EElementType.Steel, EElementType.Steel), 0.5f },
            { (EElementType.Steel, EElementType.Psychic), 1f },
            { (EElementType.Steel, EElementType.Fairy), 2f },

            { (EElementType.Psychic, EElementType.Grass), 1f },
            { (EElementType.Psychic, EElementType.Water), 1f },
            { (EElementType.Psychic, EElementType.Fire), 0.5f },
            { (EElementType.Psychic, EElementType.Ice), 1f },
            { (EElementType.Psychic, EElementType.Electric), 1f },
            { (EElementType.Psychic, EElementType.Ground), 1f },
            { (EElementType.Psychic, EElementType.Fly), 1f },
            { (EElementType.Psychic, EElementType.Ghost), 1f },
            { (EElementType.Psychic, EElementType.Fighting), 2f },
            { (EElementType.Psychic, EElementType.Steel), 0.5f },
            { (EElementType.Psychic, EElementType.Psychic), 1f },
            { (EElementType.Psychic, EElementType.Fairy), 1f },

        };

    public static float GetMultiplier(EElementType attack, EElementType defend)
    {
        return _chart.TryGetValue((attack, defend), out float multiplier)
            ? multiplier
            : 1f;
    }
}