public enum ESkillId
{
    None = 0,
    Ember = 1,
    FlameWheel = 2,
    Overheat = 3,
    AquaRing = 4,
    Surf = 5,
    LeafBlade = 6,
    RazorLeaf = 7,
    Blizzard = 8,
    IceBeam = 9,
    Earthquake = 10,
    SandsearStorm = 11,
    Charge = 12,
    Thunderbolt = 13,
    DrainingKiss = 14,
    Moonblast = 15,
    AuraSphere = 16,
    CloseCombat = 17,
    ShadowBall = 18,
    ShadowForce = 19,
    Psychic = 20,
    Psystrike = 21,
    FlashCannon = 22,
    IronDefense = 23
}